# Generated by Django 4.2.3 on 2023-07-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_options_alter_vehiculo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.IntegerField(max_length=20, verbose_name='Precio'),
        ),
    ]
