# Generated by Django 4.2.3 on 2023-07-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_options_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('member', 'Es miembro'),)},
        ),
    ]
