# Generated by Django 4.2.3 on 2023-07-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'visualizar_catalogo'), ('can_add_vehiculo', 'can_add_vehiculo'))},
        ),
    ]
