# Generated by Django 4.2.2 on 2023-07-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0007_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'Puede visualizar Catálogo de Vehiculos'), ('can_add_vehiculo', 'Puede Agregar Vehiculos'))},
        ),
    ]
